### ISSUE TITLE
UiCalendar - there is no update to the UI when a day is selected

### ISSUE THREAD

**Issue by beerinho** [goods/ember-assembly#14]
When you click a date in the UiCalendar, there is no obvious change to the UI, so it's difficult to see which date has been selected, this is the same for "single", "multiple" and "range" selection types.

**Comment by kylenathan** [comment]
I dont think this is right. It certainly shows what is selected for multiple dates (see below). Can you provide an example with code please?

![image](https://user-images.githubusercontent.com/371930/90235393-21bffb80-de19-11ea-8bad-1078f3f35946.png)

**Comment by beerinho** [comment]
Will close this, I wasn't invoking the component correctly
