### ISSUE TITLE
Build issues in Octane app when using ember-assembly

### ISSUE THREAD

**Issue by beerinho** [goods/ember-assembly#18]
I have tried a few times to add ember-assembly to an octane app I've been working on but had issues when building due to some of the package versions used in ember-assembly.

I was able to get things building correctly and working as intended by updating the package versions in the ember-assembly yarn.lock

**Comment by kylenathan** [comment]
Hi @beerinho - could you add a bit more detail about the issues you were experiencing?

**Comment by kylenathan** [comment]
Assembly appears to be working with Octane apps now.
